# Generated by Django 4.1.6 on 2023-04-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtags',
            name='tag',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
