# Generated by Django 4.1.6 on 2023-04-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='nxcms', max_length=50)),
                ('footer_text', models.CharField(default='Created by Balázs Nagy - 2023', max_length=200)),
            ],
        ),
    ]
